language: node_js
node_js:
- node
- lts/*
script:
- node ./internals/scripts/generate-templates-for-linting
- npm test -- --maxWorkers=4
- npm run build
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
notifications:
  email:
    on_failure: change
after_success: npm run coveralls
cache:
  directories:
  - node_modules
deploy:
  provider: s3
  bucket: hratx-thesis
  region: us-east-2
  local_dir: build
  access_key_id: "AKIAJ7YHT67VY56AWVBQ"
  secret_access_key:
        - secure: "GaOz47zj2rEyIC18yU+4ptlkZ3WXYeU28sEIhFAP8RpjaeZ+3lWXeE0hHPyJAWsH3JokKWGJkBgsSka9oGqGlW68WqVNhaFfk2NxcAlOHxvjRmzsuURZuTJHD0SkeR37z8fzsyfSaAYVvLm8bjCsqAz4VJb1Z56au81EXtdwavQw1KNnmSIxrhOhLRAd456Qwj0rw1xsxQcEBKESValccKU83aVKoPmX6HclF7QSCCkRBxEEAc8JhTnAmuc64bczg0XhE30CJXm5wfnQPLZ4ur6iPbaD5jEEk16PqYcwQgyPzT0fsKJBgXhmTaWtGTWvpMfk/7xfgI/uWN+50+rzxLuRLK7RzkokIazCFWQzj8kuv6PfAhITaICC5nTlRLRnt4UQ/oVCBot2Bn8O03+zZDHjBRAS+w+MhibXxDstDxI3bKaPC1fuqyprIWv/q9kHYqLPfDbpHv6zsitUMfXuNRx7ggyxKgHMkcOYbj9L0W5Ow0P1GEzciFXfddsKWLLZJWgrU4Pt2EIxoY5L2eFiN5vgVyKaU34Ohcuyg+dNIEoKrBpvx9uZ7BEM5CDjyp1uOaV9hasXxzntLzhSeiey6AdmAjy9aZYobZZHGjn+UsHuVt1B+A/gvTtR8o4sCk7SzZ6cn/cgJ2t9ANQw8cbWKI8/y/KUOEPCrsqkdPISnsM="
  skip_cleanup: true
