language: node_js
node_js:
  - node
  - lts/*
script:
  - node ./internals/scripts/generate-templates-for-linting
  - npm test -- --maxWorkers=4
  - npm run build
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
notifications:
  email:
    on_failure: change
after_success: npm run coveralls
cache:
  directories:
    - node_modules
deploy:
  provider: s3
  bucket: hratx-thesis
  region: us-east-2
  local_dir: build
  access_key_id: 'AKIAJ7YHT67VY56AWVBQ'
  secret_access_key:
    secure: 'NYD4554mT8Y5bQNcH27wDxEPSQVuHevl6YQBvdNWbdibxJwIrOch50X+FxeIS6ylKh3udtYoy3iWkWEgCJzbLE+EFyRbOwPCwZ8OfchvVOdQ3W2XLVdQtB1Ean8/OqDxadvp0fSQWJSBRp7rsS9G/TL5i0dL0IUPZ8RTX63Pm/91GgZU1mi67zmhq5Fln3cqPLDhkct9aXv9z20bTC1vOEb/HQE9N6x6VoKfpO0i1k54322qr0ALdtK8i+/ck+NMp20uFZFkBkxc+9UQnVqMiA0KDLVxQfrwxTdm7XVaGtllxpV8FXjvxzz5PVM26h442s92JFNS80j2tFpWDZrYfGYuNzN0+78My1y+TVLhq93lm3M9hH3Zries4SpLdEWzV2nOKV1bTuMVeKT2wXNdaBAISa7RDpK1kR1HT0YxiP5TFdI5++xYKtQH8hg27ReZbxlyW1jyNdcmLTM/N2ID5j2MCg5erMgsBWos5xZyv3eozoPNTIjG6VvWLvosrkEpOJkHsF8YcfgZ3sz1C5ftyVj0UzA3VidZjWgzU3enUDByg7fBHeClApmMS6wTFv4Fpvyv/N42IvfAralj+qljcCCVKx7dwIwYG41gg/oseMHCzjW/Kb1bKnPbAnZizLHKl00peEbHh+B+7XoZvoVdXoAA/4FDKoioUofN9MlGYyc='
  skip_cleanup: true
