language: node_js
node_js:
  - node
  - lts/*
script:
  - node ./internals/scripts/generate-templates-for-linting
  - npm test -- --maxWorkers=4
  - npm run build
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
notifications:
  email:
    on_failure: change
after_success: npm run coveralls
cache:
  directories:
    - node_modules
deploy:
  provider: s3
  region: us-east-2
  local_dir: build
  access_key_id: AKIAJ7YHT67VY56AWVBQ
  secret_access_key:
    secure: j6QZCu6urAs+wThfjicFwLSrKBDLmMfw10N8lkbIbbRDYQ15ZR6VuhCtEpjYuf+m/nk1zjOyvd4iDgRs4ZUkDjFM8mEE2nS4zyGvT4n46IkDJseor+M8xwwr+jvrQ/pw+fBdGNSHvAKZYoTjOGx8xFjoRGWKr3UDxzDe0HiRPv1WLHT93uP1dOKdwirVjEwbeagFs/l6bgUW4g4EX8DhdA5E+h2q1VFJP8TSSUtv/VNVKyGTxpu80iZSL6jc/uAIbhHjxTsCai0qx8r5rpdBWj3RbRuZEBC5hjXpfk70SiyPoAe1R3trgL44nn0QlisbFRaSudjqcvyWaGyZ7FgTaNiVIUaM3kJZCcpeGRG4Lwx76LPMeTMWu/iNJDBp5pdeOD9KKh5U/Ap1o7K23EHzi274MggLK0hs1F03lmj//hyVFGAweQXEs2+s5KzY9RV/w+PoMBnJwoHCXl+JFAAPYuOT6AK3X0C9Px2fDuciF4Y/nWTx6IBHuuH1a6eO/jTSsl5mzTkAezNT2Kg+RFMAdzCQVXsOeT7UcwYXWK0217zeIFIm1ImpLMX4TAXB2wH+R1ysZHcJ4Nz5+BbpTLNogoaVDlX8PH4qsWKPU3IXRiG0xpK6NbCNHmWbSp2Zt+D92/cRd4W6zXI4zT5C0sC8yI2qzfWM7hesynb/SHUc4tE=
  bucket: hratx-thesis
  acl: bucket_owner_full_control
  skip_cleanup: true
