version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - /home/jpw/thesis/inventor-io/proxy/conf.d/default.conf
    ports:
      - '80:80'
  inventorio:
    image: jpwarren13/inventor-io:latest
    container_name: inventorio
    expose:
      - '3000'
